### ISSUE TITLE
CRMint Measurement Protocol detected as "bot" by Google Analytics

### ISSUE THREAD

**Issue by gckabuto** [google-marketing-solutions/crmint#183]
I was wondering why I had so many discrepancies between my BQ table for Measurement Protocol and actual data in GA when I figured out my GA view had option checked:

![image](https://user-images.githubusercontent.com/62604172/88411537-69ce9e00-cdd8-11ea-9639-265ac76abba2.png)

After unchecking it, I had no more discrepancies so I believe the CRMint BQtoMeasurementProtocol job is detected as a "bot" by GA. 

Maybe you guys could talk to GA teams to allow this job to send hit to GA even when this option is on :)

**Comment by hampussanden** [comment]
It's possible to have this boxed checked without getting any descrepansies if you add user agent to your hit. Here's a link to the documentation: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ua

**Comment by blackwire** [comment]
Closing this as answered.
