### ISSUE TITLE
StorageToBQImporter Field delimiter

### ISSUE THREAD

**Issue by PatrickProgrammads** [google-marketing-solutions/crmint#229]
Hi,
I'm configuring a pipeline that should send data from a CSV file stocked in Storage to BQ.
The CSV file is stocked by a client in the Storage. While setting up the pipeline, I found out the the CSV actually uses a semicolon as a delimiter instead of a comma. In BigQuery I can specify the delimiter and my import works smoothly, however, I'm not able to define it in my CRMInt worker.
Is there a way I can define the delimiter in the worker or do I need to customize the code for this usecase?
Thanks in advance for your help !

**Comment by blackwire** [comment]
At this point, I'd recommend either loading the data via BigQuery: https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-csv#sql

Or using the BigQuery Data Transfer options available in Google Cloud:
https://console.cloud.google.com/bigquery/transfers/configs/create
