### ISSUE TITLE
Running into issues re-deploying an instance in same project (KeyError: 'migrate_sql_conn_name')

### ISSUE THREAD

**Issue by aazimh** [google-marketing-solutions/crmint#422]
Hi all,

I deployed a CRMint instance in a project of mine last week to test - everything went perfectly, but after the test I saw I was still being charged for certain elements so I tried to 'clean up' the instance by deleting the obvious components, i.e. the Cloud SQL database and the Cloud Run instances. I thought it would be fairly easy to re-deploy in the future if needed using the install script as it was quite simple the first time around.

Fast forward to today and when I try to run the install script I'm running into a few errors, as there were a lot of hidden deployments that I didn't delete the first time around. The script seems to be erroring out on these but still continuing, so I'm assuming those are okay. However, there is one error that it cannot seem to get past and that I cannot figure out how to fix:

```
>>>> Sync database
---> Get current project identifier ✓
     Project ID found: xxxx-xxxx-xxx-xxx
---> Initialize Terraform ✓
---> List Terraform workspaces ✓
---> Select existing Terraform workspace: xxxx-xxxx-xxx-xxx ✓
---> Retrieve configuration ✓
Traceback (most recent call last):
  File "/opt/venv/bin/crmint", line 33, in <module>
    sys.exit(load_entry_point('crmint', 'console_scripts', 'crmint')())
  File "/app/cli/appcli.py", line 118, in entry_point
    cli()
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/cli/commands/bundle.py", line 39, in install
    ctx.invoke(cloud.migrate, debug=debug)
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/cli/commands/cloud.py", line 425, in migrate
    _run_command(
  File "/app/cli/commands/cloud.py", line 416, in _run_command
    trigger_command(cmd, outputs, debug=debug)
  File "/app/cli/commands/cloud.py", line 261, in trigger_command
    db_conn_name = outputs['migrate_sql_conn_name']['value']
KeyError: 'migrate_sql_conn_name'
```

I assume this has to do with the fact that I previously deleted the SQL database, but how can I force the script to create one from scratch? I deleted the 'cloud_db_uri' secret, but that didn't do anything. I assume there is something somewhere that's telling the script not to build the database from scratch, but I can't figure out what that might be.

If anyone is able to help on how to fix this error, or how to re-deploy CRMint from step zero within a project that might have some steps already created, I would be very grateful. Thank you!

**Comment by dulacp** [comment]
Hi @aazimh,

Thanks for reporting this issue, actually the error is the result of another error which happened before that.

Can you please re-run `crmint cloud setup --debug` in your CloudShell and copy-paste the complete output here?

> You might be limited by CloudShell buffer here, if that's the case, you need to:
>    1. capture the entire output with this: `output=$(crmint cloud setup --debug) && echo $output > output.log`
>    1. After that you can download this file with: `cloudshell download output.log`

Thanks for your help!

Pierre

**Comment by aazimh** [comment]
Thanks Pierre - here is the full log: https://pastebin.com/uPsa0ZpC

I removed any personal information (my email + project name), hopefully I did that properly. If I left anything important in please do let me know.

Happy to run any further steps to help you debug. Thanks!

**Comment by Adonis232** [comment]
I run into the same problem, is there a way to fix this ? 

Thx

**Comment by blackwire** [comment]
A quick note on this. We have a PR that will likely be merged soon that provides an uninstall script you can use to fully remove the pre-existing CRMint installation (to hopefully avoid any errors you might get trying to reinstall).

You can see that here: https://github.com/google-marketing-solutions/crmint/pull/470

Hopefully, this helps! Thanks to @tyroneschiff for providing this!

**Comment by blackwire** [comment]
Closing this as resolved with that uninstallation script now being merged.
