### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by haituong** [google-marketing-solutions/crmint#481]
Hi, i try to install with: crmint bundle install --debug, and it return:
Failed to connect: HTTPSConnectionPool(host='crmint.34.102.134.18.nip.io', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
Please help me

**Comment by blackwire** [comment]
It's possible you're SSL cert just took a little longer to setup or perhaps there was another error that happened during install that caused the cert to not get setup properly. You might try that URL again and see if you can access it. If you cannot then re-run the install and see if there's an error somewhere else in the process that happened.

**Comment by blackwire** [comment]
I'm going to assume this is resolved. Feel free to reach out again if you're still experiencing this issue.
