### ISSUE TITLE
Pipelines running but models and table not showing

### ISSUE THREAD

**Issue by Adonis323** [google-marketing-solutions/crmint#484]
Hi, 

I have multiple ETL's and while they seem to run correctly, when I go to BQ I see that the tables are not being created nor the models. I have updated made a git pull already but the ETL's while looking correct in CRMint UI and logs  are not writing anything on BQ. The ETL's are configured through IBQML and they dont include anythong custom. Have anyone encountered something similar? 
 I saw an issue sumilar to this one, and I followed the steps described there, and I still have the same issue

Thank you

**Comment by instant-bqml** [comment]
It's challenging to know what issue is occurring without any sort of error or log. 

Is there a way for you to manually run a pipeline on CRMint and then review the logs in the logging component of Google Cloud to evaluate if you are getting an error and what that error is?

Alternatively, I would suggest deploying CRMint in another Google Cloud project and exporting your pipelines to that project.

You can uninstall CRMint from your current project by running `crmint cloud uninstall`
