### ISSUE TITLE
New user access

### ISSUE THREAD

**Issue by Adonis323** [google-marketing-solutions/crmint#486]
Hi I have CRMint running and I would like to grant access to a new collague, I can't seem to find the command to do it, is possible to grant access to the UI once it is created ??

Thanks in advance

**Comment by blackwire** [comment]
It is. You can use the crmint tool that you used to install it to manage user access.
`crmint bundle allow-users email1@example.com,email2@example.com`

If this doesn't work for you then I believe you can search "identity-aware proxy" in the Google Cloud search bar at the top then check all 3 of your CRMint services and you'll see "IAP-secured Web App User" and under that should be your existing users. When adding a principal for these services this is the role you'll want to grant new users in order for them to be able to access the site.

Using the CLI tool is a lot more straightforward so if you have that option I would go that route.
