### ISSUE TITLE
ETL'S stuck and not running

### ISSUE THREAD

**Issue by Adonis323** [google-marketing-solutions/crmint#504]
Hi team, 

I have ran CRMint for some time now and it has been running with no issue, but since last week they have being started, at first they were not triggered by the scheduler but if I did it manually they ran with no issue, I updated the package and now they are stuck on the first step "Dataprep" indefinetly even if I run them manually, looking at the logs the only logs I see are these ones pointing at an error on the start-pipeline method. 

![image](https://github.com/google-marketing-solutions/crmint/assets/134921282/02c4fba0-2408-41cf-9389-0daf73260ca9)

I went to the cron scheduler and it is as it was created when installed by the bundle, there are no "/" in the cron job.

![Screenshot 2024-05-07 091712](https://github.com/google-marketing-solutions/crmint/assets/134921282/d37eec2e-fb5a-4b0d-afc9-e15976ee29c3)

I have deleted and uploaded the pipelines, and updated the package again, is there anything else I can do to go back to the pipelines running correctly?

Thank you in advance

**Comment by instant-bqml** [comment]
If your CRMint application is running on App Engine, I'd recommend redeploying CRMint first to ensure you have all the most updated code. You can do that by executing the following in your Cloud Shell: `bash <(curl -Ls https://raw.githubusercontent.com/instant-bqml/crmint/master/scripts/install.sh) master --bundle`

Based on your screenshots, the issue does appear to be related to an issue with the cron. After you re-redeploy the updated version of CRMint, confirm that all of your crons are formatted correctly and re-save each pipeline if possible.

If that still does not resolve the issue, you may need to login to the SQL server that maintains the pipeline logic and make updates directly there versus the frontend.

That would look something like this:

1. Login to your SQL server `crmintapp-db` -- run `gcloud sql connect crmintapp-db --user=root` in your cloud shell. To login, you'll probably need to change the password of your root which can be done from within Cloud inside the SQL instance: 
<img width="1446" alt="Screenshot 2024-05-07 at 9 59 29 AM" src="https://github.com/google-marketing-solutions/crmint/assets/78978926/3b6e35a9-825f-4f6f-8cdb-4688389fde4a">

2. Make sure that the underlying cron that is saved in the `schedules` table is valid: <img width="1079" alt="Screenshot 2024-05-07 at 10 01 27 AM" src="https://github.com/google-marketing-solutions/crmint/assets/78978926/b574f8b7-b22e-40b6-9bdb-1f0ccdf8db85">
3. If not, modify the schedules table using SQL `update` syntax.

Hopefully that helps resolve your issue. Let us know how it goes!

**Comment by Adonis323** [comment]
Thank you for all your help. I followed all the steps you gave me but still
the pipelines were not running properly, the cron jobs looked correct on
the server,

[image: image.png]

 So after trying different ways, I ended up deleting and installing the
packages again, and I managed to make it work again, but I really dont know
what went wrong, I'll do some more digging and get back to you if I find
the issue.


Anyway thank you!

On Tue, May 7, 2024 at 4:04 PM instant-bqml ***@***.***>
wrote:

> If your CRMint application is running on App Engine, I'd recommend
> redeploying CRMint first to ensure you have all the most updated code. You
> can do that by executing the following in your Cloud Shell: bash <(curl
> -Ls
> https://raw.githubusercontent.com/instant-bqml/crmint/master/scripts/install.sh
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fraw.githubusercontent.com%2Finstant-bqml%2Fcrmint%2Fmaster%2Fscripts%2Finstall.sh&e=6b687e64&h=5baa3911&f=y&p=y>)
> master --bundle
>
> Based on your screenshots, the issue does appear to be related to an issue
> with the cron. After you re-redeploy the updated version of CRMint, confirm
> that all of your crons are formatted correctly and re-save each pipeline if
> possible.
>
> If that still does not resolve the issue, you may need to login to the SQL
> server that maintains the pipeline logic and make updates directly there
> versus the frontend.
>
> That would look something like this:
>
>    1. Login to your SQL server crmintapp-db -- run gcloud sql connect
>    crmintapp-db --user=root in your cloud shell. To login, you'll
>    probably need to change the password of your root which can be done from
>    within Cloud inside the SQL instance:
>
> Screenshot.2024-05-07.at.9.59.29.AM.png (view on web)
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fgoogle-marketing-solutions%2Fcrmint%2Fassets%2F78978926%2F3b6e35a9-825f-4f6f-8cdb-4688389fde4a&e=6b687e64&h=a8904b64&f=y&p=y>
>
>    2. Make sure that the underlying cron that is saved in the schedules
>    table is valid: Screenshot.2024-05-07.at.10.01.27.AM.png (view on web)
>    <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fgoogle-marketing-solutions%2Fcrmint%2Fassets%2F78978926%2Fb574f8b7-b22e-40b6-9bdb-1f0ccdf8db85&e=6b687e64&h=294047e4&f=y&p=y>
>    3. If not, modify the schedules table using SQL update syntax.
>
> Hopefully that helps resolve your issue. Let us know how it goes!
>
> —
> Reply to this email directly, view it on GitHub
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fgoogle-marketing-solutions%2Fcrmint%2Fissues%2F504%23issuecomment-2098489257&e=6b687e64&h=b9113dd6&f=y&p=y>,
> or unsubscribe
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBAFLYQUTZPX43LICBRRLGO3ZBDNO5AVCNFSM6AAAAABHKNCX56VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOJYGQ4DSMRVG4&e=6b687e64&h=2cc0e03c&f=y&p=y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>
> --
> This message has been checked by Libraesva ESG and is found to be clean.
> Submit it as bad/spam
> <https://itex.esvacloud.com/action/4VYg4v4r2CzFpWb/submit-as-bad>
> Blocklist sender
> <https://itex.esvacloud.com/action/4VYg4v4r2CzFpWb/blocklist>



-- 

*Enmanuel Adonis Lafuente Ramos*

Data Engineer

***@***.***



<https://bit.ly/415CMwH>

[image: LinkedIn] <https://www.linkedin.com/company/incubeta>  [image:
Instagram] <https://www.instagram.com/incubetaglobal/>  [image: Twitter]
<https://twitter.com/IncubetaGlobal?s=20>  [image: YouTube]
<https://www.youtube.com/channel/UCnozDypc7kxyDrAXkpeRGpw>



CONFIDENTIALITY NOTICE: The information in this email and in any
attachments with it is intended for the addressee(s) only and may include
personal or confidential information that is legally privileged. Use of
this information by individuals other than the addressee(s) and by
individuals who are not authorized to access the information is prohibited.
If you are not the addressee or are not authorized to access the
information, then its disclosure, reproduction, distribution and/or
provision to third parties is not permitted and you are requested to send
this email back to us and to delete the original.

**Comment by Adonis323** [comment]
Issue solved
