### ISSUE TITLE
CRMint stuck sending events 

### ISSUE THREAD

**Issue by Adonis323** [google-marketing-solutions/crmint#514]
Hi everyone, 

I have multiple pipelines running leveraging  data from GA4 export, predicting purchase propensity and sending those events through MP back  to GA4. The issue I'm having since last Sunday is that all the pipelines I have are stuck sending the events for hours, and if I try to stop them manually some of them get stuck on stopping, so to stop them I have to reset all of them. Those pipelines are created using a JSON template from ibqml and nothing has changed in the data or configuration, I tried to update CRMint using the terminal and the steps described on the Wiki section but when I execute "crmint bundle update" the terminal shut down on its own.
All these issues are affecting a couple other pipelines I have with some queries, on those 2 pipelines the queries are activated but they are not executed, seems like the connection to BQ was lost or something like that.

Any help to try and fix this will be welcomed.

Thank you!

**Comment by blackwire** [comment]
Did you install this version of CRMint originally or the iBQML (https://github.com/instant-bqml/crmint) version? If you installed the later you'll need to reach out there for support as these versions have separated in their development and the steps to update may be different and the execution will likely be different.

That said, if you installed this version originally and have Cloud Run instances you can also attempt to update by simply updating the images running within them to the latest by simply re-deploying them with the same image that's set today (which should be set to the latest).

How many events is it trying to send through? There could be some other issue. Perhaps try checking cloud logs to see if there are obvious errors you can report back here.
